#!/usr/bin/env python3
"""
engine — one orchestrator CLI over the whole pipeline.

Replaces the 11-step manual runbook with stateful commands driven by
portfolio.yaml + brand.yaml + post-file frontmatter (docs/post-file-spec.md).

Usage:
    python scripts/engine.py status                       # portfolio overview
    python scripts/engine.py status --brand allsquared
    python scripts/engine.py plan --brand allsquared --week 2026-W31
    python scripts/engine.py plan --all --week 2026-W31   # every brand + relationship slots
    python scripts/engine.py validate --brand allsquared --week 2026-W31
    python scripts/engine.py approve --brand allsquared --week 2026-W31
    python scripts/engine.py schedule --brand allsquared --week 2026-W31 [--dry-run]
    python scripts/engine.py measure --brand allsquared
    python scripts/engine.py sync-notion

Status lifecycle: draft → validated → approved → scheduled/published.
The approval gate stays human: `approve` is run by a person (or by the
publish-on-merge workflow after a human merges the week PR).
"""

from __future__ import annotations

import argparse
import datetime as dt
import subprocess
import sys
from pathlib import Path

import brand_config
from brand_config import REPO_ROOT, BRANDS_DIR


# ─── status ──────────────────────────────────────────────────────────────────

def cmd_status(args) -> int:
    brands = [args.brand] if args.brand else brand_config.portfolio_brands()
    print("=== Portfolio status ===\n")
    for brand in brands:
        cfg = brand_config.load_brand(brand)
        weeks = brand_config.list_weeks(brand)
        posts = brand_config.all_posts(brand)
        counts: dict[str, int] = {}
        for p in posts:
            s = p["meta"].get("status", "draft")
            counts[s] = counts.get(s, 0) + 1
        wired = [k for k, v in cfg["platforms"].items() if v.get("account_id")]
        count_str = ", ".join(f"{k}:{v}" for k, v in sorted(counts.items())) or "no posts"
        print(f"  {brand:<12} [{cfg.get('group', '?')}/{cfg.get('sector', '?')}] "
              f"weeks={len(weeks)} posts=({count_str}) "
              f"wired={wired or 'NONE'}")
    print()
    return 0


# ─── plan ────────────────────────────────────────────────────────────────────

PLAN_STUB = """# Plan — {week} — {brand}

> Generated by `engine plan`. Fill theme + slots, draft posts as
> `post-NN-<platform>.md` per docs/post-file-spec.md, then `engine validate`.

## Theme
[1 sentence]

## Inputs
- Pattern weights: {weights_note}
- Diversity: check content-mix.md rotation (docs/diversity-rules.md)
{derived_note}
## Slots

| # | Platform | Format | Narrative | Hook | Audience |
|---|---|---|---|---|---|
| 1 |  |  |  |  |  |
"""


def cmd_plan(args) -> int:
    week = args.week or dt.date.today().strftime("%Y-W%V")
    brands = brand_config.portfolio_brands() if args.all else [args.brand]
    if not brands or brands == [None]:
        print("ERROR: --brand or --all required", file=sys.stderr)
        return 1

    portfolio = brand_config.load_portfolio()
    relationships = portfolio.get("relationships") or []

    for brand in brands:
        wd = brand_config.week_dir(brand, week)
        wd.mkdir(parents=True, exist_ok=True)
        plan_file = wd / "PLAN.md"
        if plan_file.exists():
            print(f"  = {brand}: {plan_file.relative_to(REPO_ROOT)} exists, skipping")
            continue

        weights = BRANDS_DIR / brand / "pattern-weights.md"
        weights_note = (f"see {weights.relative_to(REPO_ROOT)}"
                        if weights.exists() else "none yet (first weeks are pure exploration)")

        derived = [r for r in relationships if r.get("target") == brand]
        derived_note = ""
        if derived:
            lines = [f"- Derived slots (portfolio.yaml relationships):"]
            for r in derived:
                lines.append(f"  - reshape from `{r['source']}` "
                             f"(stagger {r.get('stagger_days', 1)}d, never verbatim)")
            derived_note = "\n".join(lines) + "\n"

        plan_file.write_text(PLAN_STUB.format(
            week=week, brand=brand, weights_note=weights_note,
            derived_note=derived_note))
        print(f"  + {brand}: {plan_file.relative_to(REPO_ROOT)}")
    return 0


# ─── validate ────────────────────────────────────────────────────────────────

def cmd_validate(args) -> int:
    import validate_post

    week = args.week or (brand_config.list_weeks(args.brand) or [None])[-1]
    if not week:
        print(f"ERROR: no weeks found for {args.brand}", file=sys.stderr)
        return 1

    posts = brand_config.list_posts(args.brand, week)
    if not posts:
        print(f"No post files in brands/{args.brand}/weeks/{week}/ "
              f"(expected post-NN-<platform>.md)")
        return 1

    brand = validate_post.load_brand_voice(args.brand)
    failed = 0
    for post in posts:
        meta = post["meta"]
        platform = meta.get("platform", "unknown")
        issues = validate_post.validate_one(
            post["caption"], platform, brand, meta.get("format"))
        rel = post["path"].relative_to(REPO_ROOT)
        if issues:
            failed += 1
            print(f"FAIL {rel}")
            for i in issues:
                print(f"     - {i}")
        else:
            print(f"OK   {rel}")
            if meta.get("status") == "draft":
                brand_config.update_post_meta(
                    post["path"], {"platform": platform, "status": "validated"})
    print(f"\n{len(posts) - failed}/{len(posts)} posts validated for {args.brand} {week}")
    return 1 if failed else 0


# ─── approve ─────────────────────────────────────────────────────────────────

def cmd_approve(args) -> int:
    week = args.week or (brand_config.list_weeks(args.brand) or [None])[-1]
    posts = brand_config.list_posts(args.brand, week)
    n = 0
    for post in posts:
        if post["meta"].get("status") == "validated":
            brand_config.update_post_meta(post["path"], {"status": "approved"})
            print(f"  approved: {post['path'].relative_to(REPO_ROOT)}")
            n += 1
    print(f"{n} post(s) approved. Next: engine schedule --brand {args.brand} --week {week}")
    return 0


# ─── schedule / publish ──────────────────────────────────────────────────────

def _append_content_mix(brand: str, meta: dict, path: Path) -> None:
    cm = BRANDS_DIR / brand / "content-mix.md"
    today = dt.date.today().isoformat()
    entry = (
        f"\n### {today} — {meta.get('platform', '?')} — {meta.get('theme', '?')}\n"
        f"- Format: {meta.get('format', '?')}\n"
        f"- Theme: {meta.get('theme', '?')}\n"
        f"- Narrative: {meta.get('narrative', '?')}\n"
        f"- Hook: {meta.get('hook', '?')}\n"
        f"- Visual: {meta.get('visual', '') or '—'}\n"
        f"- Audience: {meta.get('audience', '?')}\n"
        f"- Caption file: {path.relative_to(REPO_ROOT)}\n"
        f"- Media file: {', '.join(meta.get('media') or []) or '—'}\n"
        f"- Status: {meta.get('status')}\n"
    )
    with cm.open("a") as f:
        f.write(entry)


def cmd_schedule(args) -> int:
    week = args.week or (brand_config.list_weeks(args.brand) or [None])[-1]
    posts = [p for p in brand_config.list_posts(args.brand, week)
             if p["meta"].get("status") == "approved"]
    if not posts:
        print(f"No approved posts for {args.brand} {week}. "
              f"(engine approve, or merge the week PR, first.)")
        return 0

    published = 0
    for post in posts:
        meta = post["meta"]
        platform = meta.get("platform")
        wiring = brand_config.account_for(args.brand, platform)
        account_id = wiring.get("account_id")
        if not account_id:
            print(f"SKIP {post['path'].name}: no account_id for '{platform}' "
                  f"in brands/{args.brand}/brand.yaml")
            continue

        if args.dry_run:
            when = meta.get("schedule") or "now"
            print(f"DRY  {post['path'].name}: would send to {platform} "
                  f"account={account_id} at {when}")
            continue

        from blotato_client import BlotatoClient
        client = BlotatoClient()
        kwargs = {k: v for k, v in wiring.items() if k != "account_id" and v}
        media = [m if str(m).startswith("http") else str((REPO_ROOT / m).resolve())
                 for m in meta.get("media") or []]
        try:
            if meta.get("schedule"):
                result = client.schedule_post(
                    account_id=account_id, platform=platform,
                    text=post["caption"], scheduled_time=meta["schedule"],
                    media_urls=media, **kwargs)
                new_status = "scheduled"
            else:
                result = client.create_post(
                    account_id=account_id, platform=platform,
                    text=post["caption"], media_urls=media, **kwargs)
                new_status = "published"
            sub_id = result.get("postSubmissionId", "")
            brand_config.update_post_meta(
                post["path"], {"status": new_status, "submission_id": sub_id})
            meta["status"] = new_status
            _append_content_mix(args.brand, meta, post["path"])
            print(f"SENT {post['path'].name} → {platform} ({new_status}, sub={sub_id})")
            published += 1
        except Exception as e:
            print(f"FAIL {post['path'].name}: {e}", file=sys.stderr)

    print(f"\n{published}/{len(posts)} approved post(s) sent for {args.brand} {week}")
    return 0


# ─── measure ─────────────────────────────────────────────────────────────────

def cmd_measure(args) -> int:
    brands = [args.brand] if args.brand else brand_config.portfolio_brands()
    rc = 0
    for brand in brands:
        if not (BRANDS_DIR / brand / "performance-log.md").exists():
            print(f"  = {brand}: no performance-log.md, skipping")
            continue
        for script in ("performance_pull.py", "compare_performance.py"):
            cmd = [sys.executable, str(REPO_ROOT / "scripts" / script), "--brand", brand]
            if script == "performance_pull.py":
                cmd += ["--days", "7"]
            print(f"→ {' '.join(cmd[1:])}")
            r = subprocess.run(cmd)
            rc = rc or r.returncode
    return rc


# ─── sync-notion ─────────────────────────────────────────────────────────────

def cmd_sync_notion(args) -> int:
    cmd = [sys.executable, str(REPO_ROOT / "scripts" / "notion_sync.py")]
    return subprocess.run(cmd).returncode


# ─── main ────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(description="Content engine orchestrator")
    sub = parser.add_subparsers(dest="command", required=True)

    p = sub.add_parser("status", help="Portfolio overview")
    p.add_argument("--brand")
    p.set_defaults(func=cmd_status)

    p = sub.add_parser("plan", help="Scaffold week plan (incl. relationship slots)")
    p.add_argument("--brand")
    p.add_argument("--all", action="store_true")
    p.add_argument("--week", help="YYYY-W## (default: current week)")
    p.set_defaults(func=cmd_plan)

    p = sub.add_parser("validate", help="Validate all posts in a week")
    p.add_argument("--brand", required=True)
    p.add_argument("--week")
    p.set_defaults(func=cmd_validate)

    p = sub.add_parser("approve", help="Mark validated posts approved (human gate)")
    p.add_argument("--brand", required=True)
    p.add_argument("--week")
    p.set_defaults(func=cmd_approve)

    p = sub.add_parser("schedule", help="Send approved posts via Blotato")
    p.add_argument("--brand", required=True)
    p.add_argument("--week")
    p.add_argument("--dry-run", action="store_true")
    p.set_defaults(func=cmd_schedule)

    p = sub.add_parser("measure", help="Pull performance + pattern comparison")
    p.add_argument("--brand")
    p.set_defaults(func=cmd_measure)

    p = sub.add_parser("sync-notion", help="Push portfolio + pipeline to Notion")
    p.set_defaults(func=cmd_sync_notion)

    args = parser.parse_args()
    sys.exit(args.func(args))


if __name__ == "__main__":
    main()
